import type { IPTCField } from './types'
import { CharacterTypes } from './types'

// TODO: Add originating program and version to save, remove them from here
// TODO: Change language identifier to select with options from ISO 639:1988
// TODO: check supplement category description
// TODO: check every field tbh
// TODO: Update date and other fields better handling
// TODO: Update BaseField to use prop isntead of model as it doesnt modify

/**
 * Based on the IPTC IIM Specification Version 4.2
 * Source: https://www.iptc.org/std/IIM/4.2/specification/IIMV4.2.pdf
 */
export const iptcIimFields: IPTCField[] = [
  {
    key: '2:03',
    title: 'Object Type Reference',
    description: `
    The Object Type is used to distinguish between different types of objects within the IIM.
    The first part is a number representing a language independent international reference to an Object Type followed by a colon separator.
    The second part, if used, is a text representation of the Object Type Number (maximum 64 octets) consisting of graphic characters plus spaces either in English, as defined in the language of the service as indicated in DataSet 2:135`,
    type: 'object-type',
    octets: { min: 3, max: 67 },
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:04',
    title: 'Object Attribute Reference',
    description: `
    The Object Attribute defines the nature of the object independent of the Subject.
    The first part is a number representing a language independent international reference to an Object Attribute followed by a colon separator.
    The second part, if used, is a text representation of the Object Attribute Number (maximum 64 octets) consisting of graphic characters plus spaces either in English, as defined in the language of the service as indicated in DataSet 2:135
    A registry of Object Attribute Numbers and Names and their corresponding definitions (if available) will be maintained by theIPTC in different languages, with translations as supplied by members.`,
    type: 'object-attribute',
    octets: { min: 4, max: 68 },
    mandatory: false,
    repeatable: true,
  },
  {
    key: '2:05',
    title: 'Object Name',
    description: 'Used as a shorthand reference for the object. Changes to existing data, such as updated stories or new crops on photos, should be identified in Edit Status.',
    type: 'text',
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    octets: { max: 64 },
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:07',
    title: 'Edit Status',
    description: 'Status of the objectdata, according to the practice of the provider.',
    type: 'text',
    octets: { max: 64 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:08',
    title: 'Editorial Update',
    description: 'Indicates the type of update that this object provides to a previous object. The link to the previous object is made using the ARM (DataSets 1:120 and 1:122), according to the practices of the provider.',
    type: 'select',
    octets: 2,
    options: [
      { value: '01', label: 'Additional Language' },
    ],
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:10',
    title: 'Urgency',
    description: `
    Specifies the editorial urgency of content and not necessarily the envelope handling priority (see 1:60, Envelope Priority).
    The '1' is most urgent, '5' normal and '8' denotes the least-urgent copy. The numerals '9' and '0' are reserved for future use.`,
    type: 'slider',
    minValue: 1,
    maxValue: 8,
    minLabel: 'Most Urgent',
    maxLabel: 'Least Urgent',
    octets: 1,
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:12',
    title: 'Subject Reference',
    description: '??? will have to figure this out',
    type: 'subject-reference',
    mandatory: false,
    repeatable: true,
  },
  {
    key: '2:15',
    title: 'Category',
    description: 'Identifies the subject of the objectdata in the opinion of the provider. A list of categories will be maintained by a regional registry, where available, otherwise by the provider.',
    type: 'text',
    allowedCharacterTypes: [CharacterTypes.alphabetic],
    octets: { max: 3 },
    mandatory: false,
    repeatable: false,
    deprecated: true,
  },
  {
    key: '2:20',
    title: 'Supplemental Category',
    description: 'Supplemental categories further refine the subject of an objectdata. Only a single supplemental category may be contained in each DataSet. A supplemental category may include any of the recognised categories as used in 2:15. Otherwise, selection of supplemental categories are left to the provider.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: true,
    deprecated: true,
  },
  {
    key: '2:22',
    title: 'Fixture Identifier',
    description: 'Identifies objectdata that recurs often and predictably. Enables users to immediately find or recall such an object.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:25',
    title: 'Keywords',
    description: `
    Used to indicate specific information retrieval words. Each keyword uses a single Keywords DataSet. Multiple keywords use multiple Keywords DataSets.
    It is expected that a provider of various types of data that are related in subject matter uses the same keyword, enabling the receiving system or subsystems to search across all types of data for related material.`,
    octets: { max: 64 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: true,
  },
  {
    key: '2:26',
    title: 'Content Location Code',
    description: `
    Indicates the code of a country/geographical location referenced by the content of the object. Where ISO has established an appropriate country code under ISO 3166, that code will be used.
    When ISO3166 does not adequately provide for identification of a location or a country, e.g. ships at sea, space, IPTC will assign an appropriate threecharacter code under the provisions of ISO3166 to avoid conflicts.
    If used in the same object with DataSet 2:27, must immediately precede and correspond to it.`,
    octets: { max: 3 },
    type: 'location',
    nameKey: '2:27',
    mandatory: false,
    repeatable: true,
  },
  {
    key: '2:27',
    title: 'Content Location Name',
    octets: { max: 64 },
    description: `
    Provides a full, publishable name of a country/geographical location referenced by the content of the object, according to guidelines of the provider.
    If used in the same object with DataSet 2:26, must immediately follow and correspond to it.`,
    type: 'extra',
    mandatory: false,
    repeatable: true,
  },
  {
    key: '2:30',
    title: 'Release Date',
    description: 'Designates in the form CCYYMMDD the earliest date the provider intends the object to be used. Follows ISO 8601 standard.',
    octets: 8,
    type: 'date',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:35',
    title: 'Release Time',
    octets: 11,
    description: 'Designates in the form HHMMSS±HHMM the earliest time the provider intends the object to be used. Follows ISO 8601 standard.',
    type: 'time',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:37',
    title: 'Expiration Date',
    description: 'Designates in the form CCYYMMDD the latest date the provider or owner intends the object data to be used. Follows ISO 8601 standard.',
    octets: 8,
    type: 'date',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:38',
    title: 'Expiration Time',
    description: 'Designates in the form HHMMSS±HHMM the latest time the provider or owner intends the object data to be used. Follows ISO 8601 standard.',
    octets: 11,
    type: 'time',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:40',
    title: 'Special Instructions',
    description: 'Other editorial instructions concerning the use of the objectdata, such as embargoes and warnings.',
    octets: { max: 256 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:42',
    title: 'Action Advised',
    description: 'Indicates the type of action that this object provides to a previous object. The link to the previous object is made using the ARM (DataSets 1:120 and 1:122), according to the practices of the provider.',
    octets: 2,
    type: 'select',
    options: [
      { value: '01', label: 'Object Kill' },
      { value: '02', label: 'Object Replace' },
      { value: '03', label: 'Object Append' },
      { value: '04', label: 'Object Reference' },
    ],
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:45',
    title: 'Reference Service',
    description: '',
    octets: { max: 10 },
    allowedCharacterTypes: [CharacterTypes.graphic],
    type: 'text',
    mandatory: false,
    repeatable: true,
  },
  {
    key: '2:47',
    title: 'Reference Date',
    description: '',
    type: 'date',
    octets: 8,
    mandatory: true,
    repeatable: true,
    parent: '2:45',
  },
  {
    key: '2:50',
    title: 'Reference Number',
    description: '',
    octets: 8,
    type: 'text',
    allowedCharacterTypes: [CharacterTypes.numeric],
    mandatory: true,
    repeatable: true,
    parent: '2:45',
  },
  {
    key: '2:55',
    title: 'Date Created',
    octets: 8,
    description: 'Represented in the form CCYYMMDD to designate the date the intellectual content of the objectdata was created rather than the date of the creation of the physical representation.',
    type: 'date',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:60',
    title: 'Time Created',
    octets: 11,
    description: 'Represented in the form HHMMSS±HHMM to designate the time the intellectual content of the objectdata current sourcematerial was created rather than the creation of the physical representation. Follows ISO 8601 standard.',
    type: 'time',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:62',
    title: 'Digital Creation Date',
    description: 'Represented in the form CCYYMMDD to designate the date the digital representation of the objectdata was created.',
    octets: 8,
    type: 'date',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:63',
    title: 'Digital Creation Time',
    description: 'Represented in the form HHMMSS±HHMM to designate the time the digital representation of the objectdata was created. Follows ISO 8601 standard.',
    octets: 11,
    type: 'time',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:65',
    title: 'Originating Program',
    description: 'Identifies the type of program used to originate the objectdata.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:70',
    title: 'Program Version',
    description: 'Identifies the version of the program specified in 2:65.',
    octets: { max: 10 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
    parent: '2:65',
  },
  {
    key: '2:75',
    title: 'Object Cycle',
    description: `Where: 'a' = morning, 'p' = evening, 'b' = both. Virtually only used in North America.`,
    type: 'select',
    octets: 1,
    options: [
      { value: 'a', label: 'Morning' },
      { value: 'p', label: 'Evening' },
      { value: 'b', label: 'Both' },
    ],
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:80',
    title: 'By-line',
    description: 'Contains name of the creator of the objectdata, e.g. writer, photographer or graphic artist.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: true,
  },
  {
    key: '2:85',
    title: 'By-line Title',
    description: 'A by-line title is the title of the creator or creators of an objectdata. Where used, a by-line title should follow the by-line it modifies.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: true,
  },
  {
    key: '2:90',
    title: 'City',
    description: 'Identifies city of objectdata origin according to guidelines established by the provider.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:92',
    title: 'Sub-location',
    description: 'Identifies the location within a city from which the objectdata originates, according to guidelines established by the provider.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:95',
    title: 'Province/State',
    description: 'Identifies Province/State of origin according to guidelines established by the provider.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:100',
    title: 'Country/Primary Location Code',
    description: 'Indicates the code of the country/primary location where the intellectual property of the objectdata was created, e.g. a photo was taken, an event occurred.',
    octets: 3,
    type: 'location',
    nameKey: '2:101',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:101',
    title: 'Country/Primary Location Name',
    description: 'Provides full, publishable, name of the country/primary location where the intellectual property of the objectdata was created, according to guidelines of the provider.',
    octets: { max: 64 },
    type: 'extra',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:103',
    title: 'Original Transmission Reference',
    description: 'A code representing the location of original transmission according to practices of the provider.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:105',
    title: 'Headline',
    description: 'A publishable entry providing a synopsis of the contents of the objectdata.',
    octets: { max: 256 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:110',
    title: 'Credit',
    description: 'Identifies the provider of the objectdata, not necessarily the owner/creator.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:115',
    title: 'Source',
    description: 'The name of a person or party who has a role in the content supply chain. This could be an agency, a member of an agency, an individual or a combination. Source could be different from Creator and from the entities in the Copyright Notice.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:116',
    title: 'Copyright Notice',
    description: 'Contains any necessary copyright notice.',
    octets: { max: 128 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:118',
    title: 'Contact',
    description: 'Identifies the person or organisation which can provide further background information on the objectdata.',
    octets: { max: 128 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: true,
  },
  {
    key: '2:120',
    title: 'Caption/Abstract',
    description: 'A textual description of the objectdata, particularly used where the object is not text.',
    octets: { max: 2000 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space, CharacterTypes.return, CharacterTypes.linefeed],
    type: 'textarea',
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:122',
    title: 'Writer/Editor',
    description: 'Identification of the name of the person involved in the writing, editing or correcting the objectdata or caption/abstract.',
    octets: { max: 32 },
    allowedCharacterTypes: [CharacterTypes.graphic, CharacterTypes.space],
    type: 'text',
    mandatory: false,
    repeatable: true,
  },
  {
    key: '2:131',
    title: 'Image Orientation',
    description: 'Indicates the layout of the image area.',
    octets: 1,
    type: 'select',
    options: [
      { value: 'P', label: 'Portrait' },
      { value: 'L', label: 'Landscape' },
      { value: 'S', label: 'Square' },
    ],
    mandatory: false,
    repeatable: false,
  },
  {
    key: '2:135',
    title: 'Language Identifier',
    description: `
    Describes the major national language of the object, according to the 2-letter codes of ISO 639:1988.
    Does not define or imply any coded character set, but is used for internal routing, e.g. to various editorial desks.`,
    octets: { min: 2, max: 3 },
    type: 'language',
    mandatory: false,
    repeatable: false,
  },
]

/**
 * As per IPTC IIM Specification 4.2 - Appendix G
 * Source: https://www.iptc.org/std/IIM/4.2/specification/IIMV4.2.pdf
 */
export const objectTypes = [
  { number: '01', name: 'News' },
  { number: '02', name: 'Data' },
  { number: '03', name: 'Advisory' },
]

/**
 * As per IPTC IIM Specification 4.2 - Appendix G
 * Source: https://www.iptc.org/std/IIM/4.2/specification/IIMV4.2.pdf
 */
export const objectAttributes = [
  { number: '001', name: 'Current' },
  { number: '002', name: 'Analysis' },
  { number: '003', name: 'Archive material' },
  { number: '004', name: 'Background' },
  { number: '005', name: 'Feature' },
  { number: '006', name: 'Forecast' },
  { number: '007', name: 'History' },
  { number: '008', name: 'Obituary' },
  { number: '009', name: 'Opinion' },
  { number: '010', name: 'Polls & Surveys' },
  { number: '011', name: 'Profile' },
  { number: '012', name: 'Results Listings & Tables' },
  { number: '013', name: 'Side bar & Supporting information' },
  { number: '014', name: 'Summary' },
  { number: '015', name: 'Transcript & Verbatim' },
  { number: '016', name: 'Interview' },
  { number: '017', name: 'From the Scene' },
  { number: '018', name: 'Retrospective' },
  { number: '019', name: 'Statistics' },
  { number: '020', name: 'Update' },
  { number: '021', name: 'Wrap-up' },
  { number: '022', name: 'Press Release' },
]

/**
 * As per IPTC IIM Specification 4.2 - Appendix H
 * Source: https://www.iptc.org/std/IIM/4.2/specification/IIMV4.2.pdf
 */
export const subjects = [
  {
    number: '01',
    name: 'Arts, Culture & Entertainment',
    description: 'Matters pertaining to the advancement and refinement of the human mind, of interests, skills, tastes and emotions',
  },
  {
    number: '02',
    name: 'Crime, Law & Justice',
    description: 'Establishment and/or statement of the rules of behaviour in society, the enforcement of these rules, breaches of the rules and the punishment of offenders. Organisations and bodies involved in these activities.',
  },
  {
    number: '03',
    name: 'Disasters & Accidents',
    description: 'Man made and natural events resulting in loss of life or injury to living creatures and/or damage to inanimate objects or property.',
  },
  {
    number: '04',
    name: 'Economy, Business & Finance',
    description: 'All matters concerning the planning, production and exchange of wealth.',
  },
  {
    number: '05',
    name: 'Education',
    description: 'All aspects of furthering knowledge of human individuals from birth to death.',
  },
  {
    number: '06',
    name: 'Environmental Issues',
    description: 'All aspects of protection, damage, and condition of the ecosystem of the planet earth and its surroundings.',
  },
  {
    number: '07',
    name: 'Health',
    description: 'All aspects pertaining to the physical and mental welfare of human beings.',
  },
  {
    number: '08',
    name: 'Human Interest',
    description: 'Lighter items about individuals, groups, animals or objects.',
  },
  {
    number: '09',
    name: 'Labour',
    description: 'Social aspects, organisations, rules and conditions affecting the employment of human effort for the generation of wealth or provision of services and the economic support of the unemployed.',
  },
  {
    number: '10',
    name: 'Lifestyle & Leisure',
    description: 'Activities undertaken for pleasure, relaxation or recreation outside paid employment, including eating and travel.',
  },
  {
    number: '11',
    name: 'Politics',
    description: 'Local, regional, national and international exercise of power, or struggle for power, and the relationships between governing bodies and states.',
  },
  {
    number: '12',
    name: 'Religion & Belief',
    description: 'All aspects of human existence involving theology, philosophy, ethics and spirituality.',
  },
  {
    number: '13',
    name: 'Science & Technology',
    description: 'All aspects pertaining to human understanding of nature and the physical world and the development and application of this knowledge.',
  },
  {
    number: '14',
    name: 'Social Issues',
    description: 'Aspects of the behaviour of humans affecting the quality of life.',
  },
  {
    number: '15',
    name: 'Sport',
    description: 'Competitive exercise involving physical effort. Organisations and bodies involved in these activities.',
  },
  {
    number: '16',
    name: 'Unrest, Conflicts & War',
    description: 'Acts of socially or politically motivated protest and/or violence.',
  },
  {
    number: '17',
    name: 'Weather',
    description: 'The study, reporting and prediction of meteorological phenomena.',
  },
]

/**
 * As per IPTC IIM Specification 4.2 - Appendix I
 * Source: https://www.iptc.org/std/IIM/4.2/specification/IIMV4.2.pdf
 */
export const subjectMatters = [
  { number: '001', name: 'Archaeology', subject: '01' },
  { number: '002', name: 'Architecture', subject: '01' },
  { number: '003', name: 'Bullfighting', subject: '01' },
  { number: '004', name: 'Carnival', subject: '01' },
  { number: '005', name: 'Cinema', subject: '01' },
  { number: '006', name: 'Dance', subject: '01' },
  { number: '007', name: 'Fashion', subject: '01' },
  { number: '008', name: 'Language', subject: '01' },
  { number: '009', name: 'Libraries & Museums', subject: '01' },
  { number: '010', name: 'Literature', subject: '01' },
  { number: '011', name: 'Music', subject: '01' },
  { number: '012', name: 'Painting', subject: '01' },
  { number: '013', name: 'Photography', subject: '01' },
  { number: '014', name: 'Radio', subject: '01' },
  { number: '015', name: 'Sculpture', subject: '01' },
  { number: '016', name: 'Television', subject: '01' },
  { number: '017', name: 'Theatre', subject: '01' },

  { number: '001', name: 'Crime', subject: '02' },
  { number: '002', name: 'Judiciary', subject: '02' },
  { number: '003', name: 'Police', subject: '02' },
  { number: '004', name: 'Punishment', subject: '02' },
  { number: '005', name: 'Prison', subject: '02' },

  { number: '001', name: 'Drought', subject: '03' },
  { number: '002', name: 'Earthquake', subject: '03' },
  { number: '003', name: 'Famine', subject: '03' },
  { number: '004', name: 'Fire', subject: '03' },
  { number: '005', name: 'Flood', subject: '03' },
  { number: '006', name: 'Industrial accident', subject: '03' },
  { number: '007', name: 'Meteorological disaster', subject: '03' },
  { number: '008', name: 'Nuclear accident', subject: '03' },
  { number: '009', name: 'Pollution', subject: '03' },
  { number: '010', name: 'Transport accident', subject: '03' },
  { number: '011', name: 'Volcanic eruption', subject: '03' },

  { number: '001', name: 'Agriculture', subject: '04' },
  { number: '002', name: 'Chemicals', subject: '04' },
  { number: '003', name: 'Computing & Information Technology', subject: '04' },
  { number: '004', name: 'Construction & Property', subject: '04' },
  { number: '005', name: 'Energy & Resources', subject: '04' },
  { number: '006', name: 'Financial & Business Services', subject: '04' },
  { number: '007', name: 'Goods Distribution', subject: '04' },
  { number: '008', name: 'Macro Economics', subject: '04' },
  { number: '009', name: 'Markets', subject: '04' },
  { number: '010', name: 'Media', subject: '04' },
  { number: '011', name: 'Metal Goods & Engineering', subject: '04' },
  { number: '012', name: 'Metals & Minerals', subject: '04' },
  { number: '013', name: 'Process Industries', subject: '04' },
  { number: '014', name: 'Tourism & Leisure', subject: '04' },
  { number: '015', name: 'Transport', subject: '04' },

  { number: '001', name: 'Adult Education', subject: '05' },
  { number: '002', name: 'Further Education', subject: '05' },
  { number: '003', name: 'Parent Organisations', subject: '05' },
  { number: '004', name: 'Preschooling', subject: '05' },
  { number: '005', name: 'Schools', subject: '05' },
  { number: '006', name: 'Teachers Unions', subject: '05' },
  { number: '007', name: 'University', subject: '05' },

  { number: '001', name: 'Alternative Energy', subject: '06' },
  { number: '002', name: 'Conservation', subject: '06' },
  { number: '003', name: 'Energy Savings', subject: '06' },
  { number: '004', name: 'Environmental Politics', subject: '06' },
  { number: '005', name: 'Environmental pollution', subject: '06' },
  { number: '006', name: 'Natural resources', subject: '06' },
  { number: '007', name: 'Nature', subject: '06' },
  { number: '008', name: 'Population', subject: '06' },
  { number: '009', name: 'Waste', subject: '06' },
  { number: '010', name: 'Water Supplies', subject: '06' },

  { number: '001', name: 'Diseases', subject: '07' },
  { number: '002', name: 'Epidemic & Plague', subject: '07' },
  { number: '003', name: 'Health treatment', subject: '07' },
  { number: '004', name: 'Health organisations', subject: '07' },
  { number: '005', name: 'Medical research', subject: '07' },
  { number: '006', name: 'Medical staff', subject: '07' },
  { number: '007', name: 'Medicines', subject: '07' },
  { number: '008', name: 'Preventative medicine', subject: '07' },

  { number: '001', name: 'Animals', subject: '08' },
  { number: '002', name: 'Curiosities', subject: '08' },
  { number: '003', name: 'People', subject: '08' },

  { number: '001', name: 'Apprentices', subject: '09' },
  { number: '002', name: 'Collective contracts', subject: '09' },
  { number: '003', name: 'Employment', subject: '09' },
  { number: '004', name: 'Labour dispute', subject: '09' },
  { number: '005', name: 'Labour legislation', subject: '09' },
  { number: '006', name: 'Retirement', subject: '09' },
  { number: '007', name: 'Retraining', subject: '09' },
  { number: '008', name: 'Strike', subject: '09' },
  { number: '009', name: 'Unemployment', subject: '09' },
  { number: '010', name: 'Unions', subject: '09' },
  { number: '011', name: 'Wages & Pensions', subject: '09' },
  { number: '012', name: 'Work Relations', subject: '09' },

  { number: '001', name: 'Games', subject: '10' },
  { number: '002', name: 'Gaming & Lotteries', subject: '10' },
  { number: '003', name: 'Gastronomy', subject: '10' },
  { number: '004', name: 'Hobbies', subject: '10' },
  { number: '005', name: 'Holidays or vacations', subject: '10' },
  { number: '006', name: 'Tourism', subject: '10' },

  { number: '001', name: 'Defence', subject: '11' },
  { number: '002', name: 'Diplomacy', subject: '11' },
  { number: '003', name: 'Elections', subject: '11' },
  { number: '004', name: 'Espionage & Intelligence', subject: '11' },
  { number: '005', name: 'Foreign Aid', subject: '11' },
  { number: '006', name: 'Government', subject: '11' },
  { number: '007', name: 'Human Rights', subject: '11' },
  { number: '008', name: 'Local authorities', subject: '11' },
  { number: '009', name: 'Parliament', subject: '11' },
  { number: '010', name: 'Parties', subject: '11' },
  { number: '011', name: 'Refugees', subject: '11' },
  { number: '012', name: 'Regional authorities', subject: '11' },
  { number: '013', name: 'State Budget', subject: '11' },
  { number: '014', name: 'Treaties & Organisations', subject: '11' },

  { number: '001', name: 'Cults & sects', subject: '12' },
  { number: '002', name: 'Faith', subject: '12' },
  { number: '003', name: 'Free masonry', subject: '12' },
  { number: '004', name: 'Religious institutions', subject: '12' },

  { number: '001', name: 'Applied Sciences', subject: '13' },
  { number: '002', name: 'Engineering', subject: '13' },
  { number: '003', name: 'Human Sciences', subject: '13' },
  { number: '004', name: 'Natural Sciences', subject: '13' },
  { number: '005', name: 'Philosophical Sciences', subject: '13' },
  { number: '006', name: 'Research', subject: '13' },
  { number: '007', name: 'Scientific exploration', subject: '13' },
  { number: '008', name: 'Space programmes', subject: '13' },

  { number: '001', name: 'Addiction', subject: '14' },
  { number: '002', name: 'Charity', subject: '14' },
  { number: '003', name: 'Demographics', subject: '14' },
  { number: '004', name: 'Disabled', subject: '14' },
  { number: '005', name: 'Euthanasia', subject: '14' },
  { number: '006', name: 'Family', subject: '14' },
  { number: '007', name: 'Family planning', subject: '14' },
  { number: '008', name: 'Health insurance', subject: '14' },
  { number: '009', name: 'Homelessness', subject: '14' },
  { number: '010', name: 'Minority groups', subject: '14' },
  { number: '011', name: 'Pornography', subject: '14' },
  { number: '012', name: 'Poverty', subject: '14' },
  { number: '013', name: 'Prostitution', subject: '14' },
  { number: '014', name: 'Racism', subject: '14' },
  { number: '015', name: 'Welfare', subject: '14' },

  { number: '001', name: 'Aero and Aviation Sports', subject: '15' },
  { number: '002', name: 'Alpine Skiing', subject: '15' },
  { number: '003', name: 'American Football', subject: '15' },
  { number: '004', name: 'Archery', subject: '15' },
  { number: '005', name: 'Athletics, Track & Field', subject: '15' },
  { number: '006', name: 'Badminton', subject: '15' },
  { number: '007', name: 'Baseball', subject: '15' },
  { number: '008', name: 'Basketball', subject: '15' },
  { number: '009', name: 'Biathlon', subject: '15' },
  { number: '010', name: 'Billiards, Snooker and Pool', subject: '15' },
  { number: '011', name: 'Bobsleigh', subject: '15' },
  { number: '012', name: 'Bowling', subject: '15' },
  { number: '013', name: 'Bowls & Petanque', subject: '15' },
  { number: '014', name: 'Boxing', subject: '15' },
  { number: '015', name: 'Canoeing & Kayaking', subject: '15' },
  { number: '016', name: 'Climbing', subject: '15' },
  { number: '017', name: 'Cricket', subject: '15' },
  { number: '018', name: 'Curling', subject: '15' },
  { number: '019', name: 'Cycling', subject: '15' },
  { number: '020', name: 'Dancing', subject: '15' },
  { number: '021', name: 'Diving', subject: '15' },
  { number: '022', name: 'Equestrian', subject: '15' },
  { number: '023', name: 'Fencing', subject: '15' },
  { number: '024', name: 'Field Hockey', subject: '15' },
  { number: '025', name: 'Figure Skating', subject: '15' },
  { number: '026', name: 'Freestyle Skiing', subject: '15' },
  { number: '027', name: 'Golf', subject: '15' },
  { number: '028', name: 'Gymnastics', subject: '15' },
  { number: '029', name: 'Handball (Team)', subject: '15' },
  { number: '030', name: 'Horse Racing, Harness Racing', subject: '15' },
  { number: '031', name: 'Ice Hockey', subject: '15' },
  { number: '032', name: 'Jai Alai (Pelota)', subject: '15' },
  { number: '033', name: 'Judo', subject: '15' },
  { number: '034', name: 'Karate', subject: '15' },
  { number: '035', name: 'Lacrosse', subject: '15' },
  { number: '036', name: 'Luge', subject: '15' },
  { number: '037', name: 'Marathon', subject: '15' },
  { number: '038', name: 'Modern Pentathlon', subject: '15' },
  { number: '039', name: 'Motor Racing', subject: '15' },
  { number: '040', name: 'Motor Rallying', subject: '15' },
  { number: '041', name: 'Motorcycling', subject: '15' },
  { number: '042', name: 'Netball', subject: '15' },
  { number: '043', name: 'Nordic Skiing', subject: '15' },
  { number: '044', name: 'Orienteering', subject: '15' },
  { number: '045', name: 'Polo', subject: '15' },
  { number: '046', name: 'Power Boating', subject: '15' },
  { number: '047', name: 'Rowing', subject: '15' },
  { number: '048', name: 'Rugby League', subject: '15' },
  { number: '049', name: 'Rugby Union', subject: '15' },
  { number: '050', name: 'Sailing', subject: '15' },
  { number: '051', name: 'Shooting', subject: '15' },
  { number: '052', name: 'Ski Jumping', subject: '15' },
  { number: '053', name: 'Snow Boarding', subject: '15' },
  { number: '054', name: 'Soccer', subject: '15' },
  { number: '055', name: 'Softball', subject: '15' },
  { number: '056', name: 'Speed Skating', subject: '15' },
  { number: '057', name: 'Speedway', subject: '15' },
  { number: '058', name: 'Sports Organisations', subject: '15' },
  { number: '059', name: 'Squash', subject: '15' },
  { number: '060', name: 'Sumo Wrestling', subject: '15' },
  { number: '061', name: 'Surfing', subject: '15' },
  { number: '062', name: 'Swimming', subject: '15' },
  { number: '063', name: 'Table Tennis', subject: '15' },
  { number: '064', name: 'Taekwon-Do', subject: '15' },
  { number: '065', name: 'Tennis', subject: '15' },
  { number: '066', name: 'Triathlon', subject: '15' },
  { number: '067', name: 'Volleyball', subject: '15' },
  { number: '068', name: 'Water Polo', subject: '15' },
  { number: '069', name: 'Water Skiing', subject: '15' },
  { number: '070', name: 'Weightlifting', subject: '15' },
  { number: '071', name: 'Windsurfing', subject: '15' },
  { number: '072', name: 'Wrestling', subject: '15' },

  { number: '001', name: 'Acts of terror', subject: '16' },
  { number: '002', name: 'Armed conflict', subject: '16' },
  { number: '003', name: 'Civil unrest', subject: '16' },
  { number: '004', name: 'Coup d\'Etat', subject: '16' },
  { number: '005', name: 'Guerrilla activities', subject: '16' },
  { number: '006', name: 'Massacre', subject: '16' },
  { number: '007', name: 'Riots', subject: '16' },
  { number: '008', name: 'Violent demonstrations', subject: '16' },
  { number: '009', name: 'War', subject: '16' },

  { number: '001', name: 'Forecasts', subject: '17' },
  { number: '002', name: 'Global change', subject: '17' },
  { number: '003', name: 'Reports', subject: '17' },
  { number: '004', name: 'Statistics', subject: '17' },
  { number: '005', name: 'Warnings', subject: '17' },
]

/**
 * As per IPTC IIM Specification 4.2 - Appendix J
 * Source: https://www.iptc.org/std/IIM/4.2/specification/IIMV4.2.pdf
 */
export const subjectDetails = [
  { number: '001', name: 'Arable Farming', subjectMatter: '001', subject: '04' },
  { number: '002', name: 'Fishing Industry', subjectMatter: '001', subject: '04' },
  { number: '003', name: 'Forestry & Timber', subjectMatter: '001', subject: '04' },
  { number: '004', name: 'Livestock Farming', subjectMatter: '001', subject: '04' },

  { number: '001', name: 'Biotechnology', subjectMatter: '002', subject: '04' },
  { number: '002', name: 'Fertilisers', subjectMatter: '002', subject: '04' },
  { number: '003', name: 'Health & Beauty products', subjectMatter: '002', subject: '04' },
  { number: '004', name: 'Inorganic chemicals', subjectMatter: '002', subject: '04' },
  { number: '005', name: 'Organic chemicals', subjectMatter: '002', subject: '04' },
  { number: '006', name: 'Pharmaceuticals', subjectMatter: '002', subject: '04' },
  { number: '007', name: 'Synthetics & Plastics', subjectMatter: '002', subject: '04' },

  { number: '001', name: 'Hardware', subjectMatter: '003', subject: '04' },
  { number: '002', name: 'Networking', subjectMatter: '003', subject: '04' },
  { number: '003', name: 'Satellite technology', subjectMatter: '003', subject: '04' },
  { number: '004', name: 'Semiconductors & active components', subjectMatter: '003', subject: '04' },
  { number: '005', name: 'Software', subjectMatter: '003', subject: '04' },
  { number: '006', name: 'Telecommunications Equipment', subjectMatter: '003', subject: '04' },
  { number: '007', name: 'Telecommunications Services', subjectMatter: '003', subject: '04' },

  { number: '001', name: 'Heavy construction', subjectMatter: '004', subject: '04' },
  { number: '002', name: 'House building', subjectMatter: '004', subject: '04' },
  { number: '003', name: 'Real Estate', subjectMatter: '004', subject: '04' },

  { number: '001', name: 'Alternative energy', subjectMatter: '005', subject: '04' },
  { number: '002', name: 'Coal', subjectMatter: '005', subject: '04' },
  { number: '003', name: 'Oil & Gas - Downstream activities', subjectMatter: '005', subject: '04' },
  { number: '004', name: 'Oil & Gas - Upstream activities', subjectMatter: '005', subject: '04' },
  { number: '005', name: 'Nuclear power', subjectMatter: '005', subject: '04' },
  { number: '006', name: 'Electricity Production & Distribution', subjectMatter: '005', subject: '04' },
  { number: '007', name: 'Waste Management & Pollution Control', subjectMatter: '005', subject: '04' },
  { number: '008', name: 'Water Supply', subjectMatter: '005', subject: '04' },

  { number: '001', name: 'Accountancy & Auditing', subjectMatter: '006', subject: '04' },
  { number: '002', name: 'Banking', subjectMatter: '006', subject: '04' },
  { number: '003', name: 'Consultancy Services', subjectMatter: '006', subject: '04' },
  { number: '004', name: 'Employment Agencies', subjectMatter: '006', subject: '04' },
  { number: '005', name: 'Healthcare Providers', subjectMatter: '006', subject: '04' },
  { number: '006', name: 'Insurance', subjectMatter: '006', subject: '04' },
  { number: '007', name: 'Legal services', subjectMatter: '006', subject: '04' },
  { number: '008', name: 'Market research', subjectMatter: '006', subject: '04' },
  { number: '009', name: 'Stock broking', subjectMatter: '006', subject: '04' },

  { number: '001', name: 'Clothing', subjectMatter: '007', subject: '04' },
  { number: '002', name: 'Department stores', subjectMatter: '007', subject: '04' },
  { number: '003', name: 'Food', subjectMatter: '007', subject: '04' },
  { number: '004', name: 'Mail Order', subjectMatter: '007', subject: '04' },
  { number: '005', name: 'Retail', subjectMatter: '007', subject: '04' },
  { number: '006', name: 'Speciality stores', subjectMatter: '007', subject: '04' },
  { number: '007', name: 'Wholesale', subjectMatter: '007', subject: '04' },

  { number: '001', name: 'Central Banks', subjectMatter: '008', subject: '04' },
  { number: '002', name: 'Consumer Issues', subjectMatter: '008', subject: '04' },
  { number: '003', name: 'Debt Markets', subjectMatter: '008', subject: '04' },
  { number: '004', name: 'Economic Indicators', subjectMatter: '008', subject: '04' },
  { number: '005', name: 'Emerging Markets Debt', subjectMatter: '008', subject: '04' },
  { number: '006', name: 'Foreign Exchange Markets', subjectMatter: '008', subject: '04' },
  { number: '007', name: 'Government Aid', subjectMatter: '008', subject: '04' },
  { number: '008', name: 'Government Debt', subjectMatter: '008', subject: '04' },
  { number: '009', name: 'Interest Rates', subjectMatter: '008', subject: '04' },
  { number: '010', name: 'International Economic Institutions', subjectMatter: '008', subject: '04' },
  { number: '011', name: 'International Trade Issues', subjectMatter: '008', subject: '04' },
  { number: '012', name: 'Loan Markets', subjectMatter: '008', subject: '04' },

  { number: '001', name: 'Energy', subjectMatter: '009', subject: '04' },
  { number: '002', name: 'Metals', subjectMatter: '009', subject: '04' },
  { number: '003', name: 'Securities', subjectMatter: '009', subject: '04' },
  { number: '004', name: 'Soft Commodities', subjectMatter: '009', subject: '04' },

  { number: '001', name: 'Advertising', subjectMatter: '010', subject: '04' },
  { number: '002', name: 'Books', subjectMatter: '010', subject: '04' },
  { number: '003', name: 'Cinema', subjectMatter: '010', subject: '04' },
  { number: '004', name: 'News Agencies', subjectMatter: '010', subject: '04' },
  { number: '005', name: 'Newspaper & Magazines', subjectMatter: '010', subject: '04' },
  { number: '006', name: 'Online', subjectMatter: '010', subject: '04' },
  { number: '007', name: 'Public Relations', subjectMatter: '010', subject: '04' },
  { number: '008', name: 'Radio', subjectMatter: '010', subject: '04' },
  { number: '009', name: 'Satellite & Cable Services', subjectMatter: '010', subject: '04' },
  { number: '010', name: 'Television', subjectMatter: '010', subject: '04' },

  { number: '001', name: 'Aerospace', subjectMatter: '011', subject: '04' },
  { number: '002', name: 'Automotive Equipment', subjectMatter: '011', subject: '04' },
  { number: '003', name: 'Defence Equipment', subjectMatter: '011', subject: '04' },
  { number: '004', name: 'Electrical Appliances', subjectMatter: '011', subject: '04' },
  { number: '005', name: 'Heavy engineering', subjectMatter: '011', subject: '04' },
  { number: '006', name: 'Industrial components', subjectMatter: '011', subject: '04' },
  { number: '007', name: 'Instrument engineering', subjectMatter: '011', subject: '04' },
  { number: '008', name: 'Shipbuilding', subjectMatter: '011', subject: '04' },

  { number: '001', name: 'Building materials', subjectMatter: '012', subject: '04' },
  { number: '002', name: 'Gold & Precious Materials', subjectMatter: '012', subject: '04' },
  { number: '003', name: 'Iron & Steel', subjectMatter: '012', subject: '04' },
  { number: '004', name: 'Non ferrous metals', subjectMatter: '012', subject: '04' },

  { number: '001', name: 'Alcoholic Drinks', subjectMatter: '013', subject: '04' },
  { number: '002', name: 'Food', subjectMatter: '013', subject: '04' },
  { number: '003', name: 'Furnishings & Furniture', subjectMatter: '013', subject: '04' },
  { number: '004', name: 'Paper & packaging products', subjectMatter: '013', subject: '04' },
  { number: '005', name: 'Rubber products', subjectMatter: '013', subject: '04' },
  { number: '006', name: 'Soft Drinks', subjectMatter: '013', subject: '04' },
  { number: '007', name: 'Textiles & Clothing', subjectMatter: '013', subject: '04' },
  { number: '008', name: 'Tobacco', subjectMatter: '013', subject: '04' },

  { number: '001', name: 'Casinos & Gambling', subjectMatter: '014', subject: '04' },
  { number: '002', name: 'Hotels & accommodation', subjectMatter: '014', subject: '04' },
  { number: '003', name: 'Recreational & Sports goods', subjectMatter: '014', subject: '04' },
  { number: '004', name: 'Restaurants & catering', subjectMatter: '014', subject: '04' },
  { number: '005', name: 'Tour operators', subjectMatter: '014', subject: '04' },

  { number: '001', name: 'Air Transport', subjectMatter: '015', subject: '04' },
  { number: '002', name: 'Railway', subjectMatter: '015', subject: '04' },
  { number: '003', name: 'Road Transport', subjectMatter: '015', subject: '04' },
  { number: '004', name: 'Waterway & Maritime Transport', subjectMatter: '015', subject: '04' },
]
